#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Script for generating fake repositories from definition files"
  echo "takes 2 params:"
  echo "  1st - pulp id of the repo"
  echo "  2nd - path to the directory with repo definition"
  echo "  3nd - path to the directory with packages (if don't want to have them generated by the script)"
  exit
fi

repo_id=$1
dir=$2

#create the repository
pulp-admin auth login --username admin --password admin
pulp-admin repo create --id $repo_id

packages_dir=$3

if [ -z "$packages_dir" ]; then
  packages_dir=$dir/packages
  mkdir $packages_dir

  #batch build packages
  ./batch_create_dummy_packages.sh $dir/packagelist.txt $packages_dir
  ./sign_dummy_package.sh $packages_dir/*.rpm
fi

pulp-admin content upload -r $repo_id --nosig -v $packages_dir/*rpm

#create groups and categories
./create_repogroups.sh $repo_id $dir/grouplist.txt

#create errata
./batch_create_errata.sh $repo_id $dir/errata.txt $packages_dir

#TODO: upload additional files


pulp-admin repo generate_metadata --id $repo_id

if [ -e "$dir/packages" ]; then
  rm -r $dir/packages
fi
