export const HOST_COLLECTIONS_KEY = 'HOST_COLLECTIONS';

export const HOST_COLLECTIONS_CREATE = 'HOST_COLLECTIONS_CREATE';
export const HOST_COLLECTIONS_COPY = 'HOST_COLLECTIONS_COPY';
export const HOST_COLLECTIONS_DELETE = 'HOST_COLLECTIONS_DELETE';

export const API_OPERATIONS = {
  CREATE: 'create',
  COPY: 'copy',
  DELETE: 'delete',
};
