export const ORGANIZATION_PRODUCTS_KEY = 'organizationProducts';

export const ORGANIZATION_PRODUCTS_REQUEST = 'ORGANIZATION_PRODUCTS_REQUEST';
export const ORGANIZATION_PRODUCTS_SUCCESS = 'ORGANIZATION_PRODUCTS_SUCCESS';
export const ORGANIZATION_PRODUCTS_FAILURE = 'ORGANIZATION_PRODUCTS_FAILURE';
