export const AVAILABLE_HOST_COLLECTIONS_KEY = 'AVAILABLE_HOST_COLLECTIONS';
export const REMOVABLE_HOST_COLLECTIONS_KEY = 'REMOVABLE_HOST_COLLECTIONS';
export const ALTER_HOST_HOST_COLLECTIONS_KEY = 'ALTER_HOST_HOST_COLLECTIONS';
export const MODAL_TYPES = {
  ADD: 'ADD',
  REMOVE: 'REMOVE',
};
