export const ANSIBLE_COLLECTIONS_REQUEST = 'ANSIBLE_COLLECTIONS_REQUEST';
export const ANSIBLE_COLLECTIONS_SUCCESS = 'ANSIBLE_COLLECTIONS_SUCCESS';
export const ANSIBLE_COLLECTIONS_ERROR = 'ANSIBLE_COLLECTIONS_ERROR';
