
# TODO: Fix these problems in our code and remove/edit the rules below

LineLength:
  Max: 200 # set to something more reasonable when fixed

ParameterLists:
  Max: 20 # remove once fixed

CollectionMethods:
  # remove this once we pick either map or collect, inject or reduce, etc
  PreferredMethods: {}

StringLiterals:
  Enabled: false # consider turning this one back on

SpaceAroundBraces:
  Enabled: false # remove me

RedundantSelf:
  Enabled: false # remove me

CaseIndentation:
  Enabled: false # remove me

Encoding:
  Enabled: false # remove me?

RedundantReturn:
  Enabled: false # remove me

SpaceInsideParens:
  Enabled: false # remove me?

SpaceAroundOperators:
  Enabled: false # remove me

EmptyLines:
  Enabled: false # remove me

SpaceInsideHashLiteralBraces:
  Enabled: false # remove me

Void:
  Enabled: false # remove me

BlockNesting:
  Enabled: false # remove me

AvoidPerlBackrefs:
  Enabled: false # remove me

Documentation:
  Enabled: false # remove me

Semicolon:
  Enabled: false # remove me

# end TODO

AllCops:
  Excludes:
    - script/rails
    - script/thin
    - db/schema.rb
    # TODO: remove these other paths as we fix them
    - app/models/**
    - app/lib/**
    - app/controllers/api/**
    - app/helpers/**
    - spec/**
    - test/**
    - integration_spec/**

MethodLength:
  Description: 'Avoid methods longer than 30 lines of code.'
  Max: 30 # default is 10

SpaceInsideHashLiteralBraces:
  EnforcedStyleIsWithSpaces: false

HashSyntax:
  Enabled: false # don't force 1.9 hash syntax

SpaceInsideHashLiteralBraces:
  Enabled: false # allow spaces (eg { :a => 1 })

LeadingCommentSpace:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RescueModifier:
  Enabled: false

AssignmentInCondition:
  Enabled: false

FavorUnlessOverNegatedIf:
  Enabled: false

WhileUntilModifier:
  Enabled: false

AlignParameters:
  Enabled: false # don't care if parameters are not aligned

ParenthesesAroundCondition:
  Enabled: false

DotPosition:
  Enabled: false

Lambda:
  Enabled: false # don't require -> for single line lambdas

HashMethods:
  Enabled: false # we use Configuration#has_key? which rubocop mistakes for the hash method

FavorSprintf:
  Enabled: false # we use % for i18n
