
# TODO: Fix these problems in our code and remove/edit the rules below

LineLength:
  Max: 200 # set to 100

ParameterLists:
  Max: 10 # set to 4

CollectionMethods:
  # remove this once we pick either map or collect, inject or reduce, etc
  PreferredMethods: {}

StringLiterals:
  Enabled: false # remove me

SpaceAroundBraces:
  Enabled: false # remove me

BlockNesting:
  Enabled: false # change to 4

AvoidPerlBackrefs:
  Enabled: false # remove me

# end TODO

AllCops:
  Excludes:
    - script/rails
    - script/thin
    - db/schema.rb
    # TODO: remove these other paths as we fix them
    - spec/**
    - test/**

MethodLength:
  Description: 'Avoid methods longer than 30 lines of code.'
  Max: 30 # default is 10

SpaceInsideHashLiteralBraces:
  EnforcedStyleIsWithSpaces: false

HashSyntax:
  Enabled: false # don't force 1.9 hash syntax

SpaceInsideHashLiteralBraces:
  Enabled: false # allow spaces (eg { :a => 1 })

LeadingCommentSpace:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RescueModifier:
  Enabled: false

AssignmentInCondition:
  Enabled: false

FavorUnlessOverNegatedIf:
  Enabled: false

WhileUntilModifier:
  Enabled: false

AlignParameters:
  Enabled: false # don't care if parameters are not aligned

ParenthesesAroundCondition:
  Enabled: false

DotPosition:
  Enabled: false

Lambda:
  Enabled: false # don't require -> for single line lambdas

HashMethods:
  Enabled: false # we use Configuration#has_key? which rubocop mistakes for the hash method

FavorSprintf:
  Enabled: false # we use % for i18n

ReduceArguments:
  Enabled: false # good rule of thumb but not worth enforcing

RedundantSelf:
  Enabled: false

RedundantReturn:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false # we allow spaces inside hash brackets

Documentation:
  Enabled: false # don't require documentation

Encoding:
  Enabled: false # don't require utf-8 encoding on every file
