
# TODO: Fix these problems in our code and remove/edit the rules below

LineLength:
  Max: 200 # set to something more reasonable when fixed

ParameterLists:
  Max: 20 # remove once fixed

CollectionMethods:
  PreferredMethods:
    # remove this once we pick either map or collect, inject or reduce, etc
    detect: 'find'

StringLiterals:
  Enabled: false # consider turning this one back on

SpaceAroundBraces:
  Enabled: false # remove me

DotPosition:
  Enabled: false # remove me

RedundantSelf:
  Enabled: false # remove me

CaseIndentation:
  Enabled: false # remove me

Encoding:
  Enabled: false # remove me?

RedundantReturn:
  Enabled: false # remove me

SpaceInsideParens:
  Enabled: false # remove me?

SpaceAroundOperators:
  Enabled: false # remove me

EmptyLines:
  Enabled: false # remove me

SpaceInsideHashLiteralBraces:
  Enabled: false # remove me

Void:
  Enabled: false # remove me

BlockNesting:
  Enabled: false # remove me

# end TODO

AllCops:
  Excludes:
    - script/rails
    - script/thin

SpaceInsideHashLiteralBraces:
  EnforcedStyleIsWithSpaces: false

HashSyntax:
  Enabled: false

LeadingCommentSpace:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RescueModifier:
  Enabled: false

AssignmentInCondition:
  Enabled: false
