
# TODO: Fix these problems in our code and remove/edit the rules below

LineLength:
  Max: 200 # set to something more reasonable when fixed

ParameterLists:
  Max: 20 # remove once fixed

CollectionMethods:
  PreferredMethods:
    # remove this once we pick either map or collect, inject or reduce, etc
    detect: 'find'

StringLiterals:
  Enabled: false # consider turning this one back on

SpaceAroundBraces:
  Enabled: false # remove me

DotPosition:
  Enabled: false # remove me

RedundantSelf:
  Enabled: false # remove me

CaseIndentation:
  Enabled: false # remove me

Encoding:
  Enabled: false # remove me?

RedundantReturn:
  Enabled: false # remove me

SpaceInsideParens:
  Enabled: false # remove me?

SpaceAroundOperators:
  Enabled: false # remove me

EmptyLines:
  Enabled: false # remove me

SpaceInsideHashLiteralBraces:
  Enabled: false # remove me

Void:
  Enabled: false # remove me

BlockNesting:
  Enabled: false # remove me

AvoidPerlBackrefs:
  Enabled: false # remove me

Documentation:
  Enabled: false # remove me

MethodLength:
  Description: 'Avoid methods longer than 20 lines of code.'
  Max: 20 # remove me to use the default of 10 lines

Semicolon:
  Enabled: false # remove me

# end TODO

AllCops:
  Excludes:
    - script/rails
    - script/thin
    - db/schema.rb
    # TODO: remove these other paths as we fix them
    - app/models/**
    - app/lib/**
    - app/controllers/**
    - app/helpers/**
    - spec/**
    - test/**
    - integration_spec/**
    - config/**
    - engines/**

SpaceInsideHashLiteralBraces:
  EnforcedStyleIsWithSpaces: false

HashSyntax:
  Enabled: false

LeadingCommentSpace:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RescueModifier:
  Enabled: false

AssignmentInCondition:
  Enabled: false

FavorUnlessOverNegatedIf:
  Enabled: false

WhileUntilModifier:
  Enabled: false

Lambda:
  Enabled: false # don't require -> for single line lambdas

HashMethods:
  Enabled: false # we use Configuration#has_key? which rubocop mistakes for the hash method
