
# TODO: Fix these problems in our code and remove/edit the rules below

LineLength:
  Max: 200 # set to 100

ParameterLists:
  Max: 10 # set to 4

CollectionMethods:
  # remove this once we pick either map or collect, inject or reduce, etc
  PreferredMethods: {}

StringLiterals:
  Enabled: false # remove me

SpaceAroundBlockBraces:
  Enabled: false # remove me

BlockNesting:
  Enabled: false # change to 4

PerlBackrefs:
  Enabled: false # remove me

RaiseArgs:
  Enabled: false # should we turn this on?

ClassLength:
  Enabled: false # agree on a limit and enable

IndentationWidth:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

Output:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

AlignHash:
  Enabled: false

PredicateName:
  Enabled: false # remove me

DefaultScope:
  Enabled: false # remove me?

IndentationConsistency:
  Enabled: false # remove me

TrailingComma:
  Enabled: false # remove me

ConditionPosition:
  Enabled: false # remove me

AccessorMethodName:
  Enabled: false # remove me

# end TODO

AllCops:
  RunRailsCops: true # automatically run rails cops
  Excludes:
    - script/rails
    - script/thin
    - db/migrate/20131014135042_katello_tables.rb
    - engines/bastion/node_modules/**
    - engines/bastion/vendor/assets/dev-components/**
    # TODO: remove these other paths as we fix them
    - spec/**
    - test/**
    - config/navigation.rb

MethodLength:
  Description: 'Avoid methods longer than 30 lines of code.'
  Max: 30 # default is 10

SpaceInsideHashLiteralBraces:
  EnforcedStyleIsWithSpaces: false

HashSyntax:
  Enabled: false # don't force 1.9 hash syntax

SpaceInsideHashLiteralBraces:
  Enabled: false # allow spaces (eg { :a => 1 })

LeadingCommentSpace:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RescueModifier:
  Enabled: false

AssignmentInCondition:
  Enabled: false

FavorUnlessOverNegatedIf:
  Enabled: false

WhileUntilModifier:
  Enabled: false

AlignParameters:
  Enabled: false # don't care if parameters are not aligned

ParenthesesAroundCondition:
  Enabled: false

DotPosition:
  Enabled: false

Lambda:
  Enabled: false # don't require -> for single line lambdas

FavorSprintf:
  Enabled: false # we use % for i18n

RedundantSelf:
  Enabled: false

RedundantReturn:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false # we allow spaces inside hash brackets

Documentation:
  Enabled: false # don't require documentation

Encoding:
  Enabled: false # don't require utf-8 encoding on every file

MethodCalledOnDoEndBlock:
  Enabled: true

SingleLineBlockParams:
  Enabled: false
