export const CONTENT_VIEWS_REQUEST = 'CONTENT_VIEWS_REQUEST';
export const CONTENT_VIEWS_SUCCESS = 'CONTENT_VIEWS_SUCCESS';
export const CONTENT_VIEWS_FAILURE = 'CONTENT_VIEWS_FAILURE';
export const CONTENT_VIEW_DETAILS_REQUEST = 'CONTENT_VIEW_DETAILS_REQUEST';
export const CONTENT_VIEW_DETAILS_SUCCESS = 'CONTENT_VIEW_DETAILS_SUCCESS';
export const CONTENT_VIEW_DETAILS_FAILURE = 'CONTENT_VIEW_DETAILS_FAILURE';
