# katello mapping file
---

# Supported distribution mapping for TDL name-version pairs.
# It's allowed to use * as wildcard for mapping.
#   e.g. "Red Hat Enterprise Linux* 5.8" will match both
#   "Red Hat Enterprise Linux 5.8" and "Red Hat Enterprise Linux Server 5.8"
imagefactory_naming:
    "Fedora 14": [Fedora, 14]
    "Fedora 15": [Fedora, 15]
    "Fedora 16": [Fedora, 16]
    "Fedora 17": [Fedora, 17]
    "Red Hat Enterprise Linux* 5.5": [RHEL-5, U5]
    "Red Hat Enterprise Linux* 5.6": [RHEL-5, U6]
    "Red Hat Enterprise Linux* 5.7": [RHEL-5, U7]
    "Red Hat Enterprise Linux* 5.8": [RHEL-5, U8]
    "Red Hat Enterprise Linux* 5.9": [RHEL-5, U9]
    "Red Hat Enterprise Linux* 6": [RHEL-6, 0]
    "Red Hat Enterprise Linux* 6.0": [RHEL-6, 0]
    "Red Hat Enterprise Linux* 6.1": [RHEL-6, 1]
    "Red Hat Enterprise Linux* 6.2": [RHEL-6, 2]
    "Red Hat Enterprise Linux* 6.3": [RHEL-6, 3]
    "Red Hat Enterprise Linux* 6.4": [RHEL-6, 4]

# vim: sw=4:ts=3:et
