export const TABLES_REQUEST = 'TABLES_REQUEST';
export const TABLES_SUCCESS = 'TABLES_SUCCESS';
export const TABLES_FAILURE = 'TABLES_FAILURE';

export const CREATE_TABLE = 'CREATE_TABLE';
export const CREATE_TABLE_SUCCESS = 'CREATE_TABLE_SUCCESS';
export const CREATE_TABLE_FAILURE = 'CREATE_TABLE_FAILURE';

export const UPDATE_TABLE = 'UPDATE_TABLE';
export const UPDATE_TABLE_SUCCESS = 'UPDATE_TABLE_SUCCESS';
export const UPDATE_TABLE_FAILURE = 'UPDATE_TABLE_FAILURE';
