=head1 NAME

katello-selinux-enable - enable Katello SELinux policy

=head1 SYNOPSIS

    katello-selinux-enable

=head1 DESCRIPTION

The B<katello-selinux-enable> program will install and enable Katello
SELinux module and sets required SELinux bool flags.

The program is called by Katello installer B<katello-configure> and it
is not usually required to run it manually.

=head1 SEE ALSO

katello-configure(1)
