export const HOST_ERRATA_KEY = 'HOST_ERRATUM';
export const HOST_ERRATA_APPLICABILITY_KEY = 'HOST_ERRATA_APPLICABILITY';
export const HOST_ERRATA_APPLY_KEY = 'HOST_ERRATUM_APPLY';

export default HOST_ERRATA_KEY;
