export const CONTENT_KEY = 'CONTENT';

export const CONTENT_TYPES_KEY = 'CONTENT_TYPES';

export const CONTENT_ID_KEY = 'CONTENT_ID';

export const REPOSITORY_CONTENT_ID_KEY = 'REPOSITORY_CONTENT_ID';
