const FLATPAK_REMOTES_KEY = 'FLATPAK_REMOTES';
export const CREATE_FLATPAK_REMOTES_KEY = 'CREATE_FLATPAK_REMOTES_KEY';
export const FLATPAK_CREATE_MODAL_ID = 'FLATPAK_CREATE_MODAL_ID';
export default FLATPAK_REMOTES_KEY;
