=head1 NAME

katello - Katello command line tool

=head1 SYNOPSIS

  katello [options] command [parameter1] [parameterN] ...
      [ -h | --help ]
      [ -u | --username ]
      [ -p | --password ]
      [ --host ]

Commands and parameters are described bellow.

=head1 DESCRIPTION

The B<katello> program is an command line application for interaction with
Katello instance. It can be used by Katello administrators and users to
execute regular tasks. There is a built-in shell avaiable that can be used
for scripting purposes.

=head1 COMMANDS

=over 2


THE_USAGE

For more information about commands and particular action please use:

  katello command action --help

or use our documentation (CLI guide).

=back

=head1 VERSION

THE_VERSION

=head1 SEE ALSO

katello-configure(8)
