=head1 NAME

katello-debug-certificates - Utility to print debug x509 information

=head1 SYNOPSIS

  katello-debug-certificates

=head1 DESCRIPTION

The B<katello-debug-certificates> script prints various important information
on the standard ouput that can be useful for debugging x509 related issues.
It is safe to use this tool, it does not printy any sensitive data like private
keys.

=head1 VERSION

THE_VERSION

=head1 SEE ALSO

katello(1)
