export const SUBSCRIPTIONS_REQUEST = 'SUBSCRIPTIONS_REQUEST';
export const SUBSCRIPTIONS_SUCCESS = 'SUBSCRIPTIONS_SUCCESS';
export const SUBSCRIPTIONS_FAILURE = 'SUBSCRIPTIONS_FAILURE';

export const UPDATE_QUANTITY_REQUEST = 'UPDATE_QUANTITY_REQUEST';
export const UPDATE_QUANTITY_SUCCESS = 'UPDATE_QUANTITY_SUCCESS';
export const UPDATE_QUANTITY_FAILURE = 'UPDATE_QUANTITY_FAILURE';

export const SUBSCRIPTIONS_QUANTITIES_REQUEST = 'SUBSCRIPTIONS_QUANTITIES_REQUEST';
export const SUBSCRIPTIONS_QUANTITIES_SUCCESS = 'SUBSCRIPTIONS_QUANTITIES_SUCCESS';
export const SUBSCRIPTIONS_QUANTITIES_FAILURE = 'SUBSCRIPTIONS_QUANTITIES_FAILURE';

export const DELETE_SUBSCRIPTIONS_REQUEST = 'DELETE_SUBSCRIPTIONS_REQUEST';
export const DELETE_SUBSCRIPTIONS_SUCCESS = 'DELETE_SUBSCRIPTIONS_SUCCESS';
export const DELETE_SUBSCRIPTIONS_FAILURE = 'DELETE_SUBSCRIPTIONS_FAILURE';

export const SUBSCRIPTIONS_EXPORT_CSV = 'SUBSCRIPTIONS_EXPORT_CSV';

export const SUBSCRIPTIONS_OPEN_MANIFEST_MODAL = 'SUBSCRIPTIONS_OPEN_MANIFEST_MODAL';
export const SUBSCRIPTIONS_CLOSE_MANIFEST_MODAL = 'SUBSCRIPTIONS_CLOSE_MANIFEST_MODAL';

export const SUBSCRIPTIONS_OPEN_DELETE_MODAL = 'SUBSCRIPTIONS_OPEN_DELETE_MODAL';
export const SUBSCRIPTIONS_CLOSE_DELETE_MODAL = 'SUBSCRIPTIONS_CLOSE_DELETE_MODAL';

export const SUBSCRIPTIONS_DISABLE_DELETE_BUTTON = 'SUBSCRIPTIONS_DISABLE_DELETE_BUTTON';
export const SUBSCRIPTIONS_ENABLE_DELETE_BUTTON = 'SUBSCRIPTIONS_ENABLE_DELETE_BUTTON';

export const SUBSCRIPTIONS_UPDATE_SEARCH_QUERY = 'SUBSCRIPTIONS_UPDATE_SEARCH_QUERY';

export const SUBSCRIPTIONS_START_MONITORING_MANIFEST_TASKS =
  'SUBSCRIPTIONS_START_MONITORING_MANIFEST_TASKS';
export const SUBSCRIPTIONS_STOP_MONITORING_MANIFEST_TASKS =
  'SUBSCRIPTIONS_STOP_MONITORING_MANIFEST_TASKS';
export const SUBSCRIPTIONS_RUN_MONITOR_MANIFEST_TASKS_MANUALLY =
  'SUBSCRIPTIONS_RUN_MONITOR_MANIFEST_TASKS_MANUALLY';
export const SUBSCRIPTIONS_START_MONITORING_MANIFEST_TASKS_FAILED =
  'SUBSCRIPTIONS_START_MONITORING_MANIFEST_TASKS_FAILED';

export const SUBSCRIPTIONS_MONITOR_TASKS_ID = 'SUBSCRIPTIONS_MONITOR_TASKS_ID';

export const SUBSCRIPTIONS_BLOCKING_FOREMAN_TASK_TYPES = [
  'Actions::Katello::Organization::ManifestImport',
  'Actions::Katello::Organization::ManifestRefresh',
  'Actions::Katello::Organization::ManifestDelete',
  'Actions::Katello::UpstreamSubscriptions::BindEntitlements',
  'Actions::Katello::UpstreamSubscriptions::UpdateEntitlement',
  'Actions::Katello::UpstreamSubscriptions::RemoveEntitlements',
  'Actions::Katello::UpstreamSubscriptions::UpdateEntitlements',
];

export const SUBSCRIPTIONS_MONITOR_TASKS_INTERVAL = 10000;
