# candlepin uses camel case in their API so just disable snake case checking
# in this folder

inherit_from:
  - ../../../../.rubocop.yml

SymbolName:
  Enabled: false

MethodAndVariableSnakeCase:
  Enabled: false