export const HOST_PACKAGES_KEY = 'HOST_PACKAGES';
export const PACKAGES_SEARCH_QUERY = 'Packages search query';
export const SELECTED_UPDATE_VERSIONS = 'Selected update versions';

export const PACKAGES_VERSION_STATUSES = {
  UPGRADABLE: 'Upgradable',
  UP_TO_DATE: 'Up-to date',
};

export const VERSION_STATUSES_TO_PARAM = {
  [PACKAGES_VERSION_STATUSES.UPGRADABLE]: 'upgradable',
  [PACKAGES_VERSION_STATUSES.UP_TO_DATE]: 'up-to-date',
};

export const PACKAGES_PERSISTENCE_STATUSES = {
  TRANSIENT: 'Transient',
  PERSISTENT: 'Persistent',
  UNKNOWN: 'Unknown',
};

// Persistence parameter values (shared with backend)
export const PERSISTENCE_PARAM_TRANSIENT = 'transient';
export const PERSISTENCE_PARAM_PERSISTENT = 'persistent';
export const PERSISTENCE_PARAM_NIL = 'nil';

export const PERSISTENCE_STATUSES_TO_PARAM = {
  [PACKAGES_PERSISTENCE_STATUSES.TRANSIENT]: PERSISTENCE_PARAM_TRANSIENT,
  [PACKAGES_PERSISTENCE_STATUSES.PERSISTENT]: PERSISTENCE_PARAM_PERSISTENT,
  [PACKAGES_PERSISTENCE_STATUSES.UNKNOWN]: PERSISTENCE_PARAM_NIL,
};
