export default {
  name: __('Name'),
  description: __('Description'),
  virt_who: __('Requires Virt-Who'),
  consumed: __('Consumed'),
  start_date: __('Starts'),
  end_date: __('Ends'),
  product_id: __('Product ID'),
  contract_number: __('Contract Number'),
  account_number: __('Account Number'),
  support_level: __('Support Level'),
  support_type: __('Support Type'),
  arch: __('Architecture(s)'),
  type: __('Type'),
  mutli_entitlement: __('Multi-entitlement'),
  stacking_id: __('Stacking ID'),
};
