#!/bin/bash
usage() {
cat <<USAGE
usage: $0 options

Simple script for creating random passphrase for katello-passwd.
It is used by katello-installer and can be used when recovering
a backup (passphrase is not stored in the backup).

OPTIONS:
  -f       Force re-creation of new passphrase
  -h       This screen

USAGE
}

FORCE=0

while getopts "f" opt; do
  case $opt in
    f)
      FORCE=1
      ;;
    h)
      usage
      exit
      ;;
    ?)
      echo "Invalid option: $OPTARG" >&2
      usage
      exit
      ;;
  esac
done

# prevent passphrase from being world-readable
umask 0007

FILE=/etc/katello/secure/passphrase
[ $FORCE -eq 0 -a -f $FILE ] && \
  echo "Passphrase file was already generated, you can only generate once" && exit 1
PASS=$(</dev/urandom tr -dc A-Za-z0-9 | head -c 64)
echo "$PASS" > $FILE

chgrp katello-shared $FILE
