#!/bin/bash

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

SRV=/sbin/service

if [ -f /etc/sysconfig/katello ]; then
  # load configuration values
  . /etc/sysconfig/katello
else
  echo "Katello does not seem to be installed on this machine" 1>&2
  exit 1
fi

# default configuration values (should be the same as in our sysv init script)
KATELLO_HOME=${KATELLO_HOME:-/usr/share/katello}
KATELLO_ENV=${KATELLO_ENV:-production}
DEPLOYMENT="katello"

if [ $KATELLO_PREFIX = "/headpin" -o $KATELLO_PREFIX = "/sam" ] ; then
    DEPLOYMENT="sam"
fi

echo -e "\n"
echo '***********************************************************'
echo "THIS SCRIPT WILL ERASE KATELLO / CANDLEPIN / PULP DATABASES"
echo '***********************************************************'
echo -e "\n"
echo "All data from all systems will be erased completely!"
echo -e "\n"
echo "This script only works with PostgreSQL database."
echo -e "\n"
echo "It is strongly recommended to back up databases:"
if [ $DEPLOYMENT = "katello" ] ; then
    echo " # mongodump --db pulp_database --out - > pulp_database.json"
fi
echo " # pg_dump -c candlepin > candlepin_db.sql"
echo " # pg_dump -c katello > katello_db.sql"
echo -e "\n"

FORCE=0
while getopts ":f" opt; do
  case $opt in
    f)
      FORCE=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

if [ ! "$FORCE" = "1" ]; then
  read -p "Are you sure you want to proceed (yes/no)? "
  [ "$REPLY" != "yes" ] && exit 1
fi

echo "Erasing all data..."

function stop_if_running {
  $SRV "$1" status >/dev/null && $SRV "$1" stop
}

function start_unless_running {
  $SRV "$1" status >/dev/null || $SRV "$1" start
}

echo "Stopping Katello instance"
stop_if_running katello

echo "Stopping Katello jobs instance"
stop_if_running katello-jobs

if [ $DEPLOYMENT = "katello" ] ; then
    echo "Stopping Pulp instance"
    stop_if_running pulp-server
fi

echo "Stopping Candlepin instance"
stop_if_running tomcat6

if [ $DEPLOYMENT = "katello" ] ; then
    echo "Dropping Pulp database"
    # mongo sometimes hang in F14/F15 (workaround 725601)
    #echo 'db.dropDatabase();' | mongo pulp_database
    $SRV mongod status >/dev/null && $SRV mongod stop
    rm -rf /var/lib/mongodb/pulp_database*
    $SRV mongod start

    echo "Initializing Pulp database"
    sleep 10s # let mongo initialize
    /usr/bin/pulp-migrate
fi

echo "Initializing Candlepin database"
/usr/share/candlepin/cpsetup -s

# cpsetup alters tomcat configuration, use the original
cp /etc/tomcat6/server.xml.original /etc/tomcat6/server.xml

if [ $DEPLOYMENT = "katello" ] ; then
    echo "Starting Pulp instance"
    $SRV pulp-server start
fi

echo "Starting Candlepin instance"
$SRV tomcat6 restart

echo "Initializing Katello database"
# cannot use initdb for this (BZ 745542)
pushd $KATELLO_HOME >/dev/null
RAILS_ENV=$KATELLO_ENV rake setup --trace 2>&1
popd >/dev/null

echo "Starting Katello instance"
$SRV katello start

echo "Starting Katello jobs instance"
$SRV katello-jobs start

echo "DONE. CHECK ALL THE MESSAGES ABOVE!"
