#!/usr/bin/ruby

puts "[Katello Ruby Linter] Checking ruby files."

Dir.glob( '**/*.rb' ) do |file|
  line_num = 0
  data = File.open(file).read
  data.each_line do |line|
    line_num += 1
    if !line.empty? && line =~ /\s+\s$/
      raise "File #{file} has trailing whitespace on line #{line_num}"
    end
  end
end

puts "[Katello Ruby Linter] Code has passed successfully."
