#!/usr/bin/ruby

puts "[Katello Ruby Linter] Checking ruby files."
found_error = false

Dir.glob( '**/*.rb' ) do |file|
  line_num = 0
  IO.foreach(file) do |line|
    line_num += 1
    if !line.empty? && line =~ /\s+\s$/
      print "File #{file} has trailing whitespace on line #{line_num}\n"
      found_error = true
    end
  end
end

if found_error
  raise "Errors found, see previous ouput."
else 
  puts "[Katello Ruby Linter] Code has passed successfully."
end
