#!/bin/bash
# Helpers for common steps in cli system tests

function get_repo_id() {
    echo `$CMD repo list --org="$TEST_ORG" -g | grep $FEWUPS_REPO | awk '{print $1}'`
}

# create sample package group and category
# requires $REPO_ID, $PACKAGE_GROUP_ID, $PACKAGE_GROUP_CATEGORY_ID
function create_sample_package_groups() {
    curl -k -u admin:admin  -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d \
        "{\"groupid\":\"$PACKAGE_GROUP_ID\",\"groupname\":\"test\",\"description\":\"test description\"}" -s \
        https://localhost/pulp/api/repositories/$REPO_ID/create_packagegroup/ > /dev/null

    curl  -k -u admin:admin -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d \
        "{\"categoryid\":\"$PACKAGE_GROUP_CATEGORY_ID\",\"categoryname\":\"test\",\"description\":\"test description\"}" -s \
        https://localhost/pulp/api/repositories/$REPO_ID/create_packagegroupcategory/ > /dev/null

    curl -k -u admin:admin -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d \
        "{\"categoryid\":\"$PACKAGE_GROUP_CATEGORY_ID\",\"groupid\":\"$PACKAGE_GROUP_ID\"}" -s  \
        https://localhost/pulp/api/repositories/$REPO_ID/add_packagegroup_to_category/ > /dev/null
}

