export const HOST_TRACES_KEY = 'HOST_TRACES';
export const RESOLVE_HOST_TRACES_TASK_KEY = 'RESOLVE_HOST_TRACES_TASK';
export const KATELLO_HOST_TOOLS_TRACER_KEY = 'KATELLO_HOST_TOOLS_TRACER';
export const KATELLO_TRACER_PACKAGE = 'katello-host-tools-tracer';
