export const ANSIBLE_COLLECTION_DETAILS_REQUEST = 'ANSIBLE_COLLECTION_DETAILS_REQUEST';
export const ANSIBLE_COLLECTION_DETAILS_SUCCESS = 'ANSIBLE_COLLECTION_DETAILS_SUCCESS';
export const ANSIBLE_COLLECTION_DETAILS_ERROR = 'ANSIBLE_COLLECTION_DETAILS_ERROR';
