export const MODULE_STREAM_DETAILS_REQUEST = 'MODULE_STREAM_DETAILS_REQUEST';
export const MODULE_STREAM_DETAILS_SUCCESS = 'MODULE_STREAM_DETAILS_SUCCESS';
export const MODULE_STREAM_DETAILS_FAILURE = 'MODULE_STREAM_DETAILS_FAILURE';
