embed_assets: on
javascript_compressor: yui

javascripts:
  common:
    - public/javascripts/jquery/jquery-1.6.2.js
    - public/javascripts/jquery-ui-1.8.11.custom/js/jquery-ui-1.8.11.custom.min.js
    - public/javascripts/jquery/plugins/jquery.hoverIntent.js
    - public/javascripts/jquery/plugins/jquery.ui.totop.js
    - public/javascripts/jquery-ujs/rails.js
    - public/javascripts/jquery/plugins/jquery.jnotify.js
    - public/javascripts/katello.js
    - public/javascripts/jquery/plugins/jquery.linkHover.js
    - public/javascripts/jquery/plugins/jquery.sparkline.min.js
    - public/javascripts/jquery/plugins/jquery.mousewheel.js
    - public/javascripts/jquery/plugins/jquery.jscrollpane.js
  html5:
    - public/javascripts/html5.js
  activation_key:
    - public/javascripts/activation_key.js
  activation_key_edit:
    - public/javascripts/activation_key_edit.js
  activation_key_subscriptions:
    - public/javascripts/activation_key_subscriptions.js
  content:
    - public/javascripts/content.js
    - public/javascripts/jquery/plugins/jquery.periodicalupdater.js
  plan:
    - public/javascripts/plan.js
    - public/javascripts/jquery/plugins/jquery.timepickr.js
  plan_edit:
    - public/javascripts/plan_edit.js
  env_select:
    - public/javascripts/env_select.js
  login:
    - public/javascripts/login.js
  promotion:
    - public/javascripts/promotion.js
    - public/javascripts/jquery/plugins/jquery.sortElements.js
    - public/javascripts/slidingtree.js
  changeset:
    - public/javascripts/changeset.js
  changeset_edit:
    - public/javascripts/changeset_edit.js
  subscription:
    - public/javascripts/subscription.js
    - public/javascripts/headpin.sparkline.js
  system:
    - public/javascripts/systems.js
  system_subscriptions:
    - public/javascripts/system_subscriptions.js
  system_packages:
    - public/javascripts/system_packages.js
  organization:
    - public/javascripts/organization.js
  environment_edit:
    - public/javascripts/environment_edit.js
  one_panel:
    - public/javascripts/one_panel.js
  panel:
    - public/javascripts/jquery/plugins/jquery.fancyqueries.js
    - public/javascripts/jquery/plugins/jquery.ba-resize.js
    - public/javascripts/panel.js
    - public/javascripts/jquery/plugins/jquery.ba-bbq.js
  products_repos:
    - public/javascripts/products_repos.js
  provider:
    - public/javascripts/provider.js
  provider_create:
    - public/javascripts/provider_create.js
  notices:
    - public/javascripts/notices.js
    - public/javascripts/jquery/plugins/jquery.periodicalupdater.js
  notices_list:
    - public/javascripts/notices_list.js
  password:
    - public/javascripts/jquery/plugins/jquery.simplePassMeter.js
  user:
    - public/javascripts/user.js
  user_edit:
    - public/javascripts/user_edit.js
  role:
    - public/javascripts/role.js
    - public/javascripts/slidingtree.js
    - public/javascripts/role_sliding_tree.js
  role_edit:
    - public/javascripts/jquery/plugins/jquery.sortElements.js
    - public/javascripts/role_edit.js
  sync_schedule:
    - public/javascripts/sync_schedule.js
  edit:
    - public/javascripts/jquery/plugins/jquery.jeditable.js
    - public/javascripts/jquery/plugins/jquery.jeditable.ajaxupload.js
    - public/javascripts/jquery/plugins/jquery.ajaxfileupload.js
    - public/javascripts/jquery.jeditable.custominputs.js
  edit_helpers:
    - public/javascripts/jquery.jeditable.helpers.js
  form:
    - public/javascripts/jquery/plugins/jquery.form.js
  treetable:
    - public/javascripts/jquery/plugins/jquery.treeTable.js    
  multiselect:
    - public/javascripts/jquery/plugins/jquery.ui.multiselect.js
  bbq:
    - public/javascripts/jquery/plugins/jquery.ba-bbq.js
  fancyqueries:
    - public/javascripts/jquery/plugins/jquery.fancyqueries.js
    - public/javascripts/search.js
  filtertable:
    - public/javascripts/jquery/plugins/jquery.uitablefilter.js
    - public/javascripts/filtertable.js
  scroll_pane:
    - public/javascripts/scroll_pane.js
stylesheets:
  common:
    - public/javascripts/jquery-ui-1.8.11.custom/css/custom-theme/jquery-ui-1.8.11.custom.css
    - public/stylesheets/jquery.loadmask.css
    - public/stylesheets/compiled/ie.css
    - public/stylesheets/jquery.jnotify.css
    - public/stylesheets/jquery.treeTable.css
    - public/stylesheets/jquery.jscrollpane.css
  contents:
    - public/stylesheets/compiled/sections/contents.css
  systems:
    - public/stylesheets/compiled/sections/systems.css
  orgs:
    - public/stylesheets/compiled/sections/orgs.css
  operations:
    - public/stylesheets/compiled/sections/operations.css
  dashboard:
    - public/stylesheets/compiled/sections/dashboard.css
  loginpage:
    - public/stylesheets/compiled/sections/loginpage.css
  generic:
    - public/stylesheets/compiled/sections/generic.css
  plan:
    - public/stylesheets/jquery.timepickr.css
  fancyqueries:
    - public/stylesheets/compiled/fancyqueries.css
  empty:
