# NOTE: This file is meant as an example. Installations via Puppet will create one properly configured in
#       /etc/katello/katello.yml

# see /usr/share/katello/config.katello_defaults.yml for available options

common:
  app_mode: katello

  # when adding a new logger don't forget to add it in here even if it's disabled by default
  # otherwise log trace feature won't work for such logger
  logging:
    # enable logging output inline in rails console
    console_inline: true
    # adds an extra line after each log message with information from which file:line and method
    # was this message logged
    log_trace: false
    loggers:
      sql:
        enabled: true
      app:
        enabled: true
      glue:
        enabled: true
      pulp_rest:
        enabled: true
      candlepin_rest:
        enabled: true
      candlepin_proxy:
        enabled: true
      foreman_rest:
        enabled: true
      roles:
        enabled: false
      tire_rest:
        enabled: false

#
# Production environment configuration
#
# The following configuration values override ones from the common section
#
production:
  logging:
    # colorize log including level token based on severity
    colorize: false
    # adds an extra line after each log message with information from which file:line and method
    # was this message logged
    log_trace: false
    # configuration of all loggers used in app
    loggers:
      # this logger is parent of all other loggers, by default this is the only one having appender
      # which is used by all other loggers
      root:
        # only messages with severity >= this level from all loggers will be logged
        level: info
        # file or syslog, for file variant you can specify other options below like filename,
        # pattern or rolling options
        type: file
        # 'daily', 'weekly', 'monthly' or number as seconds
        age: 'daily'
        # how many old log files to keep
        keep: 12
        # logger line pattern, you can use following macros
        #  [%c] name of the logger that generate the log event
        #  [%d] datestamp
        #  [%m] the user supplied log message
        #  [%p] PID of the current process
        #  [%r] the time in milliseconds since the program started
        #  [%T] the name of the thread Thread.current[:name]
        #  [%t] object_id of the thread
        #  [%F] filename where the logging request was issued
        #  [%L] line number where the logging request was issued
        #  [%M] method name where the logging request was issued
        #  [%X{string}] variable set using ::Logging.mdc['string'] =
        pattern: "[%5l %d %c %X{uuid} #%p] %m\n"
        # log filename for this environment, it will be placed into #{Rails.root}/log directory
        filename: "production.log"
        # you log files will be stored here
        # note when you log outside of standard rails path you won't see log output in WEBrick
        # STDOUT (usually not wanted in development)
        path: /var/log/katello
      # you can configure each logger individually, you can turn it off completely by using key
      # 'enabled' or you can adjust it's logging 'level'. If you specify level higher than root
      # logger has, messages below this level are ignored. If you specify lower level than root
      # they are still ignored but you can add appender in Katello::Logging just for this logger
      # and see these logs outside of main log.
      sql:
        level: warn
      roles:
        enabled: false
      # tire is a special case, all logs coming from it are debug level however they count depends
      # on root level configuration, e.g. root debug level will print most info from tire
      # unfortunately there is currently no better way
      tire_rest:
        enabled: false
#      app:
#       enabled: true
#      glue:
#       enabled: true
#      pulp_rest:
#       enabled: true
#      candlepin_rest:
#       enabled: true
#      candlepin_proxy:
#       enabled: true
#      foreman_rest:
#       enabled: true
#
# Development environment configuration
#
# The following configuration values override ones from the common section
#
development:
  logging:
    colorize: true
    loggers:
      root:
        level: debug
        type: file
        age: 'monthly'
        keep: 1
        pattern: "[%5l %d %c] %m\n"
        filename: "development.log"
      roles:
        enabled: false
      tire_rest:
        enabled: false


#
# Test environment configuration
#
# The following configuration values override ones from the common section
#
test:
  logging:
    colorize: true
    loggers:
      root:
        level: debug
        type: file
        age: 'monthly'
        keep: 1
        pattern: "[%5l %d %c] %m\n"
        filename: "development.log"
      roles:
        enabled: false
      tire_rest:
        enabled: false
