# This file contains default values for Katello configuration
# values can be overridden in /etc/katello/katello.yml

# Katello configuration
#
# :vim:sw=2:ts=2:et:

# Common configuration
#
# The following configuration values are the same for production, test
# and development environments. Values can be overridden bellow.
#
common:
  app_mode: katello
  use_cp: # set to true/false if you want to override default
  use_pulp: # set to true/false if you want to override default
  use_foreman: # set to true/false if you want to override default
  use_elasticsearch: # set to true/false if you want to override default
  app_name: # set a name if you want to override default

  warden: database
  ldap_roles: false
  rest_client_timeout: 30

  url_prefix: "/katello"

  # The host (i.e. fully qualified domain name) of the server.
  # This host is used by ActionMailer when generating urls sent in
  # emails from the server. For example, the host would be the fqdn portion
  # of a URL for resetting a user's password.
  host: 127.0.0.1

  # Similar to host; however, provides the port component of the URL.
  port: 3000
  use_ssl: false

  elastic_index: katello
  elastic_url: http://localhost:9200

  post_sync_url: "http://localhost:3000/katello/api/repositories/sync_complete"
  thumbslug_url: https://localhost:8088

  # Specifies the number of minutes that a password reset token will remain valid.
  password_reset_expiration: 120

  # email_reply_address is used to specify the "From:" address included
  # in emails sent from the Server.  If not specified, it will default to
  # no-reply@host, where host is the value specified above.
  email_reply_address:

  # Available language locale choices. (Note: Syntax for yaml requires a space after each comma ', ')
  # Default available locales are below
  available_locales: ["bn", "de", "en", "es", "fr", "gu", "hi", "it", "ja", "kn", "ko", "mr", "or", "pa", "pt-BR",
  "ru", "ta", "te", "zh-CN", "zh-TW"]

  simple_search_tokens: [":", " and\\b", " or\\b", " not\\b"]

  # Set to true if you want to log elastic search
  tire_log: false

  redhat_repository_url: https://cdn.redhat.com
  logical_insight: false

  #Allowed log levels: 'debug', 'info', 'warn', 'error', 'fatal'
  log_level: debug
  log_level_sql: debug

  # if you want roles permission check
  # logs printed enable the following
  allow_roles_logging: false

  # other debugging options
  debug_rest: false
  debug_pulp_proxy: false
  debug_cp_proxy: false

  # if paranoia is set to true even children of Exception will be rescued
  exception_paranoia: false

  # run yard server inside katello server
  embed_yard_documentation: false

  #setup how often you want
  #your notifications to be checked
  #for you to receive the right notifications
  #default value = 45 seconds
  #
  notification:
    polling_seconds: 120

  # Setup your UI search configuration.
  search:
    # specifies the number of search history elementsthat will be retained for users
    max_history: 5

    # specifies the number of search favorites that a user may store per search box
    max_favorites: 5

  # Setup your candlepin environment here
  candlepin:
    # refers to the url of the candlepin
    # example https://localhost:8443/candlepin
    url: https://localhost:8443/candlepin

    # Specify your oauth key and secret used to authenticate between Katello and Candlepin
    oauth_key: katello
    oauth_secret: katello

    # refers to the candlepin-ca.crt location that is needed
    # to connect to candlepin over https.This is not necessary
    # if the candlepin server is running on the same machine as katello
    # but required if the server is on a different machine.
    # In the different machine case the katello host needs to have a
    # copy of /etc/candlepin/certs/candlepin-ca.crt copied from
    # the candlepin host and the location of the copied file needs to be
    # specified here..
    ca_cert_file:

  # Setup your pulp environment here
  pulp:
    # refers to the url of the pulp
    # example https://localhost/pulp/api
    url: https://localhost/pulp/api/v2/

    # Specify your oauth key and secret used to authenticate between Katello and Pulp
    oauth_key: katello
    oauth_secret: katello

    sync_threads: 4
    bulk_load_size: 200
    # refers to the apache certificate
    # (typically /etc/pki/tls/certs/localhost.crt) location that is needed
    # to connect to pulp over https.
    ca_cert_file:

    sync_KBlimit:


  # Setup your foreman environment here
  foreman:
    # refers to the url of the Foreman (without the final '/')
    # example https://foreman.instance.company.com:443
    url: http://localhost:3001

    # Specify your oauth key and secret
    # used to authenticate between Katello and Foreman
    oauth_key: katello
    oauth_secret: katello

    # generate random password for each user created in Foreman by Katello
    # when false user can log in to Foreman UI with Katello password
    #   USE WITH CAUTION: it's for debugging
    random_password: true

  cloud_forms:
    oauth_key: cloud_forms
    oauth_secret: katello

  # Setup proxy to use when accessing CDN.
  # Katello calls CDN to retrieve list of repositories for a product
  # Uncomment in case you want this calls to go through your proxy
  cdn_proxy:
  #    host: localhost
  #    port: 3128
  #    user: username
  #    password: password


  database:
    adapter: postgresql
    host: localhost
    encoding: UTF8
    username: katello
    password: katello

#
# Production environment configuration
#
# The following configuration values override ones from the common section
#
production:
  log_level: warn
  log_level_sql: fatal
  exception_paranoia: true
  database:
    database: katello

#
# Development environment configuration
#
# The following configuration values override ones from the common section
#
development:
  embed_yard_documentation: true
  foreman:
    random_password: false
  database:
    database: katello
    min_messages: WARNING

#
# Test environment configuration
#
# The following configuration values override ones from the common section
#
test:
  database:
    database: katello-test<%= ENV['TEST_ENV_NUMBER'] %>
    min_messages: WARNING

#
# Blank environment configuration (rpm build environment)
#
# The following configuration values override ones from the common section
#
build:
