# NOTE: This file is meant as an example. Installations via Puppet will create one properly configured in
#       /etc/katello/katello.yml

# see /usr/share/katello/config.katello_defaults.yml for available options

common:
  app_mode: katello
