export const TASKS_MONITOR_STARTED = 'TASKS_MONITOR_STARTED';
export const TASKS_MONITOR_STOPPED = 'TASKS_MONITOR_STOPPED';
export const TASKS_MONITOR_SUCCESS = 'TASKS_MONITOR_SUCCESS';
export const TASKS_MONITOR_FAILED = 'TASKS_MONITOR_FAILED';
export const TASKS_MONITOR_ALREADY_MONITORED = 'TASKS_MONITOR_ALREADY_MONITORED';
