export const GET_CONTENT_CREDENTIALS_KEY = 'GET_CONTENT_CREDENTIALS';
export const CREATE_CONTENT_CREDENTIAL_KEY = 'CONTENT_CREDENTIAL_CREATE';
export const DELETE_CONTENT_CREDENTIAL_KEY = 'CONTENT_CREDENTIAL_DELETE';
export const CONTENT_CREDENTIAL_CERT_TYPE = 'cert';
export const CONTENT_CREDENTIAL_GPG_TYPE = 'gpg_key';
