#!/bin/bash

echo "THIS SCRIPT WILL ERASE KATELLO / CANDLEPIN / PULP DATABASES"
echo -e "\n\n"
echo "It is strongly recommended to back up databases:"
echo " # mongodump --db pulp_database --out - > pulp_database.json"
echo " # pg_dump -c candlepin > candlepin_db.sql"
echo " # pg_dump -c katello > katello_db.sql"

read -p "Are you sure you want to proceed (yes/no)? "
[ "$REPLY" != "yes" ] && exit 1

echo "ERASING!"
exit 0 # WIP

echo "Stopping Katello instance"
service katello stop

echo "Stopping Pulp instance"
service pulp-server stop

echo "Stopping Candlepin instance"
service tomcat6 stop

echo "Dropping Pulp database"
# mongo sometimes hang in F14/F15 (725601)
#echo 'db.dropDatabase();' | mongo pulp_database
service mongod stop
rm -rf /var/lib/mongodb/pulp_database
service mongod start

echo "Initializing Pulp database"
/usr/bin/pulp-migrate

echo "Initializing Candlepin database"
/usr/share/candlepin/cpsetup -s

echo "Starting Pulp instance"
service pulp-server start

echo "Starting Candlepin instance"
service tomcat6 start

echo "Initializing Katello database"
rm -f /var/lib/katello/initdb_done
service katello initdb

echo "Starting Katello instance"
service katello start

