const SMART_PROXY_CONTENT_KEY = 'SMART_PROXY_CONTENT';
export const SMART_PROXY_KEY = 'SMART_PROXY';
export const SMART_PROXY_COUNTS_UPDATE_KEY = 'SMART_PROXY_COUNTS_UPDATE_KEY';
export const SMART_PROXY_REPAIR_CONTENT_KEY = 'SMART_PROXY_REPAIR_CONTENT_KEY';
export const SMART_PROXY_CONTENT_COUNT_TASK_KEY = 'SMART_PROXY_CONTENT_COUNT_TASK';
export const SMART_PROXY_SYNC_TASK_KEY = 'SMART_PROXY_SYNC_TASK';
export const SMART_PROXY_PENDING_COUNTS_KEY = 'SMART_PROXY_PENDING_COUNTS';

export const CAPSULE_CONTENT_SYNC_STARTED_EVENT = 'katello:capsuleContentSyncStarted';
export const CAPSULE_CONTENT_SYNC_CHANGED_EVENT = 'katello:capsuleContentSyncChanged';

export const UPDATE_CONTENT_COUNTS_LABEL = 'Actions::Katello::CapsuleContent::UpdateContentCounts';

export const CONTENT_POLL_INTERVAL_MS = 4000;
export const COUNTS_POLL_INTERVAL_MS = 3000;
export const COUNTS_GRACE_PERIOD_MS = 3000;
export const COUNTS_POLL_TIMEOUT_MS = 120000;

export default SMART_PROXY_CONTENT_KEY;
