const SMART_PROXY_CONTENT_KEY = 'SMART_PROXY_CONTENT';
export const SMART_PROXY_KEY = 'SMART_PROXY';
export const SMART_PROXY_COUNTS_UPDATE_KEY = 'SMART_PROXY_COUNTS_UPDATE_KEY';
export const SMART_PROXY_REPAIR_CONTENT_KEY = 'SMART_PROXY_REPAIR_CONTENT_KEY';
export default SMART_PROXY_CONTENT_KEY;
