#!/usr/bin/ruby

require 'optparse'
require 'fileutils'

options = {:kt_home => File.expand_path("../..", __FILE__)}

OptionParser.new do |opts|
  opts.banner = <<BANNER
This script installs Gemfile.lock into the correct directory depending on your
OS. Currently, we support F16, F17, and RHEL6. If you do not have one of these
OSes, you'll be given a default Gemfile.lock. Specify your katello directory
with KT_HOME (optional).
BANNER
  opts.on("-d", "--directory KATELLO_HOME", "#{options[:kt_home]} by default") do |val|
    options[:kt_home] = val
  end

  opts.on("-h", "--help") do
    puts opts
    exit
  end
end.parse!

kt_home = options[:kt_home]

def run_command(cmd)
  puts "Running #{cmd}"
  unless system(cmd)
    STDERR.puts("Failed")
    exit 1
  end
end

if !File.exist?(kt_home)
  puts "Cannot access #{kt_home}."
  exit1
end

unless File.exists?(File.join(kt_home, "src", "Gemfile.lock"))
  os = case `cat /etc/issue`
       when /Fedora release 17/
         "f17"
       when /Fedora release 16/
         "f16"
       when /Red Hat Enterprise Linux Server release 6/
         "rhel6"
       else
         ""
       end

  os += "." unless os.length < 1 # Gemfile.XXX.lock
  gemlock = File.join(kt_home, "src", "gemfiles", "Gemfile.#{os}lock")
  gemlock_dest = File.join(kt_home, "src", "Gemfile.lock")
  run_command("ln -s #{gemlock} #{gemlock_dest}")
  puts "Installed Gemfile.lock"
else
  puts "Gemfile.lock already exists. Skipping..."
end
