export const GET_TASK_REQUEST = 'GET_TASK_REQUEST';
export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';
export const GET_TASK_FAILURE = 'GET_TASK_FAILURE';

export const TASK_BULK_SEARCH_REQUEST = 'TASK_BULK_SEARCH_REQUEST';
export const TASK_BULK_SEARCH_SUCCESS = 'TASK_BULK_SEARCH_SUCCESS';
export const TASK_BULK_SEARCH_FAILURE = 'TASK_BULK_SEARCH_FAILURE';
export const RESET_TASKS = 'RESET_TASKS';
export const POLL_TASK_INTERVAL = 5000;
