export const UPLOAD_MANIFEST_REQUEST = 'UPLOAD_MANIFEST_REQUEST';
export const UPLOAD_MANIFEST_SUCCESS = 'UPLOAD_MANIFEST_SUCCESS';
export const UPLOAD_MANIFEST_FAILURE = 'UPLOAD_MANIFEST_FAILURE';

export const REFRESH_MANIFEST_REQUEST = 'REFRESH_MANIFEST_REQUEST';
export const REFRESH_MANIFEST_SUCCESS = 'REFRESH_MANIFEST_SUCCESS';
export const REFRESH_MANIFEST_FAILURE = 'REFRESH_MANIFEST_FAILURE';

export const DELETE_MANIFEST_REQUEST = 'DELETE_MANIFEST_REQUEST';
export const DELETE_MANIFEST_SUCCESS = 'DELETE_MANIFEST_SUCCESS';
export const DELETE_MANIFEST_FAILURE = 'DELETE_MANIFEST_FAILURE';

export const MANIFEST_HISTORY_REQUEST = 'MANIFEST_HISTORY_REQUEST';
export const MANIFEST_HISTORY_SUCCESS = 'MANIFEST_HISTORY_SUCCESS';
export const MANIFEST_HISTORY_FAILURE = 'MANIFEST_HISTORY_FAILURE';

export const ENABLE_SIMPLE_CONTENT_ACCESS_REQUEST = 'ENABLE_SIMPLE_CONTENT_ACCESS_REQUEST';
export const ENABLE_SIMPLE_CONTENT_ACCESS_SUCCESS = 'ENABLE_SIMPLE_CONTENT_ACCESS_SUCCESS';
export const ENABLE_SIMPLE_CONTENT_ACCESS_FAILURE = 'ENABLE_SIMPLE_CONTENT_ACCESS_FAILURE';

export const DISABLE_SIMPLE_CONTENT_ACCESS_REQUEST = 'DISABLE_SIMPLE_CONTENT_ACCESS_REQUEST';
export const DISABLE_SIMPLE_CONTENT_ACCESS_SUCCESS = 'DISABLE_SIMPLE_CONTENT_ACCESS_SUCCESS';
export const DISABLE_SIMPLE_CONTENT_ACCESS_FAILURE = 'DISABLE_SIMPLE_CONTENT_ACCESS_FAILURE';

export const SIMPLE_CONTENT_ACCESS_ELIGIBLE_REQUEST = 'SIMPLE_CONTENT_ACCESS_ELIGIBLE_REQUEST';
export const SIMPLE_CONTENT_ACCESS_ELIGIBLE_SUCCESS = 'SIMPLE_CONTENT_ACCESS_ELIGIBLE_SUCCESS';
export const SIMPLE_CONTENT_ACCESS_ELIGIBLE_FAILURE = 'SIMPLE_CONTENT_ACCESS_ELIGIBLE_FAILURE';

// Modal IDs
export const MANAGE_MANIFEST_MODAL_ID = 'manageManifestModal';
export const DELETE_MANIFEST_MODAL_ID = 'deleteManifestModal';
