export const UPSTREAM_SUBSCRIPTIONS_KEY = 'UPSTREAM_SUBSCRIPTIONS';
export const SAVE_UPSTREAM_SUBSCRIPTIONS_KEY = 'SAVE_UPSTREAM_SUBSCRIPTIONS';

export const PING_UPSTREAM_SUBSCRIPTIONS_SUCCESS = 'PING_UPSTREAM_SUBSCRIPTIONS_SUCCESS';
export const PING_UPSTREAM_SUBSCRIPTIONS_FAILURE = 'PING_UPSTREAM_SUBSCRIPTIONS_FAILURE';
