export const UPSTREAM_SUBSCRIPTIONS_REQUEST = 'UPSTREAM_SUBSCRIPTIONS_REQUEST';
export const UPSTREAM_SUBSCRIPTIONS_SUCCESS = 'UPSTREAM_SUBSCRIPTIONS_SUCCESS';
export const UPSTREAM_SUBSCRIPTIONS_FAILURE = 'UPSTREAM_SUBSCRIPTIONS_FAILURE';
