# TODO: THESE ARE TEMPORARY CHECKS. REMOVE THIS ONCE THEY HAVE BEEN FIXED
# PROJECT WIDE
inherit_from: ../../.rubocop.yml

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/Output: # (ignore the scripts directory)
  Enabled: true

Rails/ReadWriteAttribute:
  Enabled: true

Style/AccessorMethodName:
  Enabled: true

Style/AlignHash:
  Enabled: true

Style/BracesAroundHashParameters:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/FileName:
  Enabled: true

Style/IndentHash:
  Enabled: true

Style/IndentationWidth:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/PredicateName:
  Enabled: true

Style/RaiseArgs:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

# END TODO
