export const REPOSITORY_SETS_REQUEST = 'REPOSITORY_SETS_REQUEST';
export const REPOSITORY_SETS_SUCCESS = 'REPOSITORY_SETS_SUCCESS';
export const REPOSITORY_SETS_FAILURE = 'REPOSITORY_SETS_FAILURE';

export const PRODUCT_REPOSITORY_SETS_REQUEST = 'PRODUCT_REPOSITORY_SETS_REQUEST';
export const PRODUCT_REPOSITORY_SETS_SUCCESS = 'PRODUCT_REPOSITORY_SETS_SUCCESS';
export const PRODUCT_REPOSITORY_SETS_FAILURE = 'PRODUCT_REPOSITORY_SETS_FAILURE';

export const ENABLED_REPOSITORIES_REQUEST = 'ENABLED_REPOSITORIES_REQUEST';
export const ENABLED_REPOSITORIES_SUCCESS = 'ENABLED_REPOSITORIES_SUCCESS';
export const ENABLED_REPOSITORIES_FAILURE = 'ENABLED_REPOSITORIES_FAILURE';
