export const CHANGE_CONTENT_SOURCE_DATA = 'CHANGE_CONTENT_SOURCE_DATA';
export const CHANGE_CONTENT_SOURCE_PROXY = 'CHANGE_CONTENT_SOURCE_PROXY';
export const CHANGE_CONTENT_SOURCE = 'CHANGE_CONTENT_SOURCE';
export const CHANGE_CONTENT_SOURCE_VIEWS = 'CHANGE_CONTENT_SOURCE_VIEWS';
