---
name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'KATELLO-*'

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  rubocop:
    name: Rubocop
    uses: theforeman/actions/.github/workflows/rubocop.yml@v0
    with:
      command: bundle exec rubocop --parallel --format github

  test:
    name: Ruby
    needs: rubocop
    uses: theforeman/actions/.github/workflows/foreman_plugin.yml@v0
    with:
      plugin: katello
      test_existing_database: false
      foreman_version: develop # set to the Foreman release branch after branching :)

  angular:
    name: Angular ${{ matrix.engine }} - NodeJS ${{ matrix.node }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        engine:
          - bastion
          - bastion_katello
        node:
          - '18'
    defaults:
      run:
        working-directory: "engines/${{ matrix.engine }}"
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Node ${{ matrix.node }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g grunt-cli bower
      - name: install bastion for bastion_katello
        if: ${{ matrix.engine == 'bastion_katello' }}
        run: |
          npm install --package-lock-only --no-audit --legacy-peer-deps
          npm ci --no-audit --legacy-peer-deps
        working-directory: "engines/bastion"
      - name: npm install
        run: |
          npm install --package-lock-only --no-audit --legacy-peer-deps
          npm ci --no-audit --legacy-peer-deps
      - run: grunt ci
